PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology#>
PREFIX at: <http://publications.europa.eu/ontology/authority/>

SELECT ?contract_award_notice_dentifier ?country_code ?legal_basis
WHERE {

      VALUES ?country_code { <http://publications.europa.eu/resource/authority/country/CZ> }
    # VALUES ?country_code { undef }

    # the link between contract award notice and the country code of the winner
    ?contract_award_notice epo:hasID ?contract_award_notice_id .
    ?contract_award_notice_id epo:identifierValue ?contract_award_notice_dentifier .

    ?contract_award_notice epo:summarises ?procedure .
    ?procedure epo:specifies ?lot .

    ?award_decission epo:refersTo ?lot .
    ?award_decission epo:has ?winner .
    ?winner epo:isRoleOf ?organisation .
    ?organisation epo:hasLocation ?location .
    ?location epo:hasPostalAddress ?address .
    ?address epo:hasCountryCode ?country_code .


    OPTIONAL { ?procedure epo:hasLegalBasis ?legal_basis . }

}
ORDER BY ?country_code
LIMIT 100
